### ISSUE TITLE
Missing dependency on Ubuntu 20.04: libdeflate

### ISSUE THREAD

**Issue by lorenzohess** [carnegierobotics/multisense_viewer#44]
The [documentation](https://docs.carnegierobotics.com/software/viewer.html) says to install only the following dependencies: `ffmpeg libvulkan1 policykit-1 libgtk-3-0`.

However, `libdeflate` appears to also be necessary, as I get this error, and the Viewer doesn't open:
```bash
user@host $ ./start.sh
./MultiSense-Viewer: error while loading shared libraries: libdeflate.so.0: cannot open shared object file: No such file or directory
```

Installing `libdeflate-dev` causes the error to disappear, and the Viewer opens.

**Comment by M-Gjerde** [comment]
Thank you, added this as a required dependency for Ubuntu 20.04
